#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Sun Sep  6 02:21:50 2015
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from CCMainFrame import CCMainFrame

class CaptorControlApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        CaptorControl = CCMainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(CaptorControl)
        CaptorControl.Show()
        return 1

# end of class CaptorControlApp

if __name__ == "__main__":
    gettext.install("captor_control") # replace with the appropriate catalog name

    captor_control = CaptorControlApp(0)
    captor_control.MainLoop()