#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Wed Nov 18 22:31:26 2015
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from NPMainFrame import NPMainFrame

class NPControlApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        NPControl = NPMainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(NPControl)
        NPControl.Show()
        return 1

# end of class NPControlApp

if __name__ == "__main__":
    gettext.install("np_control") # replace with the appropriate catalog name

    np_control = NPControlApp(0)
    np_control.MainLoop()